# -*- coding: utf-8 -*-
"""yi_energy_engine.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxCaQAUlC38_Ol9vzKP5pYvrJ4ITk3qp
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Project: Yi Energy (易能量演算法核心引擎)
Version: V1.0.0 (品保終審版)
Author: Zheng Yi-shen (INFJ / QA/QC Engineer)
Description: 全宇宙唯一針對 [申、子、辰、戌] 命盤與肉身大數據回測校準的能量觀測引擎。
             底層曆法標準完全對齊 JavaScript 版本 lunar.js。
"""

import datetime
from lunar_python import Lunar, Solar

class YiEnergyEngine:
    def __init__(self):
        # --- 核心規格定錨：原局地支矩陣 ---
        self.user_name = "Zheng Yi-shen"
        self.mbti = "INFJ"
        self.origin_matrix = {
            "shen": True,  # 申金 (食傷產線/前導)
            "zi": True,    # 子水 (財星核心/主線程)
            "chen": True,  # 辰土 (水庫/本體硬體)
            "xu": True     # 戌土 (火庫/自我意識)
        }

    def calculate_stresses(self, year: int, month: int, day: int, hour: int) -> dict:
        """
        核心演算法：輸入國曆時間，透過同源萬年曆轉換，計算當前時空應力
        """
        # 1. 進行曆法轉換 (對齊 lunar.js 規格)
        solar = Solar.fromYmdHms(year, month, day, hour, 0, 0)
        lunar = Lunar.fromSolar(solar)

        # 2. 提取時空四柱干支
        eight_characters = lunar.getEightChar()
        year_ganzi = eight_characters.getYear()    # 流年
        month_ganzi = eight_characters.getMonth()  # 流月
        day_ganzi = eight_characters.getDay()      # 流日
        hour_ganzi = eight_characters.getTime()    # 流時

        # 拆解天干地支
        y_gan, y_zhi = year_ganzi[0], year_ganzi[1]
        m_gan, m_zhi = month_ganzi[0], month_ganzi[1]
        d_gan, d_zhi = day_ganzi[0], day_ganzi[1]
        h_gan, h_zhi = hour_ganzi[0], hour_ganzi[1]

        all_zhi = [y_zhi, m_zhi, d_zhi, h_zhi]
        all_gan = [y_gan, m_gan, d_gan, h_gan]

        # 3. 初始化三大指標係數
        wealth_score = 1.0       # 偏財/噴寶率 (1.0 - 5.0)
        stress_score = 1.0       # 內在應力值 (1.0 - 5.0)
        system_status = "NORMAL" # 系統初始狀態
        logs = []

        # =====================================================================
        # 【演算法核心邏輯 A】：水為核心 (申子辰三合財星大匯流)
        # =====================================================================
        # 檢查時空是否引動「子水」或天干透水
        water_elements = all_zhi.count("子") + all_gan.count("壬") + all_gan.count("癸")
        if "子" in all_zhi:
            wealth_score += 2.5
            logs.append("🌊 [申子辰] 財星大潮全面解鎖：流時/日見子水引動主線程。")
        elif water_elements > 0:
            wealth_score += (water_elements * 0.8)
            logs.append(f"💰 財星浮頭：天干見 {water_elements} 重壬/癸水透出。")

        # 檢查金為前導 (申、酉時常為財氣啟動點)
        if h_zhi in ["申", "酉"]:
            wealth_score += 1.0
            logs.append(f"🔨 [金生水] 食傷產線送料：當前為 {h_zhi} 時前導，吐秀生財效率倍增。")

        # =====================================================================
        # 【演算法核心邏輯 B】：環境熔斷與轉軌 (辰戌相衝)
        # =====================================================================
        xu_count = all_zhi.count("戌")
        if xu_count > 0 and self.origin_matrix["chen"]:
            stress_score += (xu_count * 1.5)
            system_status = "TURBULENCE"
            logs.append(f"💥 [辰戌大衝] 觸發：大環境逢 {xu_count} 重戌土衝擊原局辰土水庫，不破不立。")

        # 檢查 乙庚化金 (口試畢業的壓力分流閥)
        if "乙" in all_gan and "庚" in all_gan:
            stress_score -= 1.0
            wealth_score += 0.5
            logs.append("🤝 [乙庚合金] 壓力分流閥啟動：傷官吐秀，邏輯口條極致封頂，高壓轉化為大成。")

        # =====================================================================
        # 【演算法核心邏輯 C】：靈魂定錨與身強資產固化 (火土幫身)
        # =====================================================================
        # 檢查午戌半合火局 或 未土燥土幫身
        if "午" in all_zhi and self.origin_matrix["xu"]:
            wealth_score += 0.5
            system_status = "ANCHORED"
            logs.append("🔥 [午戌半合火局] 補能：靈魂印星大點火，身強有力，固化終身核心資產。")
        if "未" in all_zhi:
            if "辰" in all_zhi or self.origin_matrix["chen"]:
                logs.append("🔨 [辰未相破] 發生：打破舊循環，全新家庭責任與資產架構建立。")

        # =====================================================================
        # 【演算法核心邏輯 D】：風險控制 (強木克土 · 惡意雜訊超載)
        # =====================================================================
        wood_count = all_zhi.count("寅") + all_zhi.count("卯")
        if wood_count >= 1:
            if "申" in all_zhi or self.origin_matrix["shen"]:
                stress_score += (wood_count * 1.2)
                system_status = "LOW_POWER_DEFENSE"
                logs.append(f"🚨 [強木克土/寅申衝] 警報：官殺體制極限施壓。")
                logs.append("🛡️ 系統啟動【低耗能防禦模式】：自動隔離外界惡意雜訊，靜待天道品保清算。")

        # 4. 良率與邊界限制 (Min/Max Clamp)
        wealth_score = min(max(wealth_score, 1.0), 5.0)
        stress_score = min(max(stress_score, 1.0), 5.0)

        # 5. 輸出產線檢驗報告
        return {
            "timestamp": f"{year}-{month:02d}-{day:02d} {hour:02d}:00",
            "ganzi_four_pillars": f"{year_ganzi}年 | {month_ganzi}月 | {day_ganzi}日 | {hour_ganzi}時",
            "wealth_score": round(wealth_score, 2),
            "stress_score": round(stress_score, 2),
            "system_status": system_status,
            "engine_logs": logs
        }

# =====================================================================
# 產線測試端 (Regression Testing / 回測與實證)
# =====================================================================
if __name__ == "__main__":
    engine = YiEnergyEngine()

    # 建立 7 大歷史黃金測試集（包含你手動更正後的真理數據）
    test_cases = [
        {"name": "2006 大大學轉軌動科 (雙戌衝辰)", "y": 2006, "m": 10, "d": 1, "h": 10},
        {"name": "2012 碩士口試畢業 (乙庚化金/雙巳)", "y": 2012, "m": 10, "d": 15, "h": 10},
        {"name": "2012 逆襲進入環保役爽缺 (雙重申子辰)", "y": 2012, "m": 12, "d": 20, "h": 10},
        {"name": "2016 牽手現任完美老婆 (雙戌任偏財/午戌合)", "y": 2016, "m": 6, "d": 9, "h": 18},
        {"name": "2016 十年偏財最高巔峰 (申子辰全量匯流)", "y": 2016, "m": 12, "d": 26, "h": 12},
        {"name": "2024 女兒降臨 (三合水局/辰未相破)", "y": 2024, "m": 2, "d": 13, "h": 9},
        {"name": "2026 2330台積電隨機買進日 (庚辰日完整財局)", "y": 2026, "m": 5, "d": 6, "h": 14}
    ]

    print("=" * 80)
    print(f" ⚙️ 啟動【Yi Energy V1.0】核心演算法引擎 - 歷史黃金特 特異點回測 (良率驗證中...)")
    print("=" * 80)

    for i, case in enumerate(test_cases, 1):
        report = engine.calculate_stresses(case["y"], case["m"], case["d"], case["h"])
        print(f"\n[測試樣本 #{i}] {case['name']}")
        print(f" ├─ 時間戳記 : {report['timestamp']}")
        print(f" ├─ 曆法輸出 : {report['ganzi_four_pillars']}")
        print(f" ├─ 噴寶指數 : {report['wealth_score']} / 5.0")
        print(f" ├─ 內在應力 : {report['stress_score']} / 5.0")
        print(f" ├─ 系統狀態 : 👑 {report['system_status']}")
        print(f" └─ 物理日誌 : ")
        for log in report['engine_logs']:
            print(f"     * {log}")
        print("-" * 80)
